mysql:
  image: mysql
  environment:
    MYSQL_ROOT_HOST: '%'
    #MYSQL_USER: admin
    #MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password
    #MYSQL_DATABASE: password
  ports:
    - '3306:3306'
  volumes:
    - ./storage/mysql:/var/lib/mysql
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
  ports:
    - '8080:80'
redis:
  image: redis
  ports:
    - '6379:6379'

