mysql:
  image: mysql
  environment:
    MYSQL_ROOT_HOST: '%'
    #MYSQL_USER: admin
    #MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password
    #MYSQL_DATABASE: password
  ports:
    - '3306:3306'
  volumes:
    - ./storage/mysql:/var/lib/mysql
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
  ports:
    - '8080:80'
redis:
  container_name: redis
  hostname: redis
  image: redis
  ports:
    - '6379:6379'
redis-commander:
  container_name: redis-commander
  hostname: redis-commander
  image: rediscommander/redis-commander:latest
  restart: always
  links:
    - redis
  environment:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DB: 4
  ports:
    - "8082:8081"
mongo:
  image: mongo
  restart: always
  ports:
    - 27017:27017
  environment:
    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: password
  volumes:
    - ./storage/mongo:/data/db
mongo-express:
  image: mongo-express
  links:
    - mongo
  restart: always
  ports:
    - 8081:8081
  environment:
    ME_CONFIG_MONGODB_ADMINUSERNAME: root
    ME_CONFIG_MONGODB_ADMINPASSWORD: password

